# Generated by Django 2.2.3 on 2019-07-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190709_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='nickname',
        ),
    ]
