# Generated by Django 2.2.3 on 2019-07-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chatuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
