# Generated by Django 2.2.3 on 2019-07-10 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190709_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='update_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
